// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfg5Ql2OSm0zIZw6X4yNzQ6__K6AFVQ9s',
    appId: '1:756089115715:web:6fb75e8e130a07da1bf0f6',
    messagingSenderId: '756089115715',
    projectId: 'qurany-6d394',
    authDomain: 'qurany-6d394.firebaseapp.com',
    storageBucket: 'qurany-6d394.firebasestorage.app',
    measurementId: 'G-RJT0YVZTVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAj65edwCJDoH7OAG4pbN6kfW7stxRP4Y',
    appId: '1:756089115715:android:749cbf6564c005e31bf0f6',
    messagingSenderId: '756089115715',
    projectId: 'qurany-6d394',
    storageBucket: 'qurany-6d394.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDnovndDzOG6m-bJlTtA8YhvIUAfKg0dk',
    appId: '1:756089115715:ios:d74fd6d8cbfb92421bf0f6',
    messagingSenderId: '756089115715',
    projectId: 'qurany-6d394',
    storageBucket: 'qurany-6d394.firebasestorage.app',
    androidClientId: '756089115715-79s6ofnv059u6v4gqlq18labiamibqej.apps.googleusercontent.com',
    iosClientId: '756089115715-jofus5u0d4phc29khd5r0q6f5qv7ptan.apps.googleusercontent.com',
    iosBundleId: 'com.example.qurany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDnovndDzOG6m-bJlTtA8YhvIUAfKg0dk',
    appId: '1:756089115715:ios:d74fd6d8cbfb92421bf0f6',
    messagingSenderId: '756089115715',
    projectId: 'qurany-6d394',
    storageBucket: 'qurany-6d394.firebasestorage.app',
    androidClientId: '756089115715-79s6ofnv059u6v4gqlq18labiamibqej.apps.googleusercontent.com',
    iosClientId: '756089115715-jofus5u0d4phc29khd5r0q6f5qv7ptan.apps.googleusercontent.com',
    iosBundleId: 'com.example.qurany',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfg5Ql2OSm0zIZw6X4yNzQ6__K6AFVQ9s',
    appId: '1:756089115715:web:c31c7fe3602c36e21bf0f6',
    messagingSenderId: '756089115715',
    projectId: 'qurany-6d394',
    authDomain: 'qurany-6d394.firebaseapp.com',
    storageBucket: 'qurany-6d394.firebasestorage.app',
    measurementId: 'G-39DYLQLHRH',
  );

}