// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgfnysNiFjPU8UcVTeNSnlRbLn2WYYUt8',
    appId: '1:19186387012:web:69b9c5c2c31240331b9411',
    messagingSenderId: '19186387012',
    projectId: 'qurany-b80ee',
    authDomain: 'qurany-b80ee.firebaseapp.com',
    storageBucket: 'qurany-b80ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUI5jN7HPVIx0Sh9UZdFxWc6fkj9iw0p8',
    appId: '1:19186387012:android:413dfafce2a19e2a1b9411',
    messagingSenderId: '19186387012',
    projectId: 'qurany-b80ee',
    storageBucket: 'qurany-b80ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhG6ZpWK_fUeCUSwOLXHGeePiovdDgeME',
    appId: '1:19186387012:ios:2af15578945adf561b9411',
    messagingSenderId: '19186387012',
    projectId: 'qurany-b80ee',
    storageBucket: 'qurany-b80ee.firebasestorage.app',
    androidClientId: '19186387012-53vegvf6ipvn4bt1cncjc6dnv6hgpuj5.apps.googleusercontent.com',
    iosClientId: '19186387012-vtu4esfenqrpo2st6ug7718022nbb4b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.qurany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhG6ZpWK_fUeCUSwOLXHGeePiovdDgeME',
    appId: '1:19186387012:ios:2af15578945adf561b9411',
    messagingSenderId: '19186387012',
    projectId: 'qurany-b80ee',
    storageBucket: 'qurany-b80ee.firebasestorage.app',
    androidClientId: '19186387012-53vegvf6ipvn4bt1cncjc6dnv6hgpuj5.apps.googleusercontent.com',
    iosClientId: '19186387012-vtu4esfenqrpo2st6ug7718022nbb4b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.qurany',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgfnysNiFjPU8UcVTeNSnlRbLn2WYYUt8',
    appId: '1:19186387012:web:8fc295130e9aec881b9411',
    messagingSenderId: '19186387012',
    projectId: 'qurany-b80ee',
    authDomain: 'qurany-b80ee.firebaseapp.com',
    storageBucket: 'qurany-b80ee.firebasestorage.app',
  );

}