import '../../feature/home/model/surah_model.dart';

class StaticSurahData {
  static List<SurahModel> getAllSurahs() {
    return [
      const SurahModel(
        number: 1,
        englishName: "Al-Fatihah",
        arabicName: "الفاتحة",
        revelationType: "MECCAN",
        totalVerses: 7,
        revealedVerses: 0,
        translation: "The Opener",
      ),
      const SurahModel(
        number: 2,
        englishName: "Al-Baqarah",
        arabicName: "البقرة",
        revelationType: "MEDINAN",
        totalVerses: 286,
        revealedVerses: 0,
        translation: "The Cow",
      ),
      const SurahModel(
        number: 3,
        englishName: "Ali 'Imran",
        arabicName: "آل عمران",
        revelationType: "MEDINAN",
        totalVerses: 200,
        revealedVerses: 0,
        translation: "Family of Imran",
      ),
      const SurahModel(
        number: 4,
        englishName: "An-Nisa",
        arabicName: "النساء",
        revelationType: "MEDINAN",
        totalVerses: 176,
        revealedVerses: 0,
        translation: "The Women",
      ),
      const SurahModel(
        number: 5,
        englishName: "Al-Ma'idah",
        arabicName: "المائدة",
        revelationType: "MEDINAN",
        totalVerses: 120,
        revealedVerses: 0,
        translation: "The Table Spread",
      ),
      const SurahModel(
        number: 6,
        englishName: "Al-An'am",
        arabicName: "الأنعام",
        revelationType: "MECCAN",
        totalVerses: 165,
        revealedVerses: 0,
        translation: "The Cattle",
      ),
      const SurahModel(
        number: 7,
        englishName: "Al-A'raf",
        arabicName: "الأعراف",
        revelationType: "MECCAN",
        totalVerses: 206,
        revealedVerses: 0,
        translation: "The Heights",
      ),
      const SurahModel(
        number: 8,
        englishName: "Al-Anfal",
        arabicName: "الأنفال",
        revelationType: "MEDINAN",
        totalVerses: 75,
        revealedVerses: 0,
        translation: "The Spoils of War",
      ),
      const SurahModel(
        number: 9,
        englishName: "At-Tawbah",
        arabicName: "التوبة",
        revelationType: "MEDINAN",
        totalVerses: 129,
        revealedVerses: 0,
        translation: "The Repentance",
      ),
      const SurahModel(
        number: 10,
        englishName: "Yunus",
        arabicName: "يونس",
        revelationType: "MECCAN",
        totalVerses: 109,
        revealedVerses: 0,
        translation: "Jonah",
      ),
      const SurahModel(
        number: 11,
        englishName: "Hud",
        arabicName: "هود",
        revelationType: "MECCAN",
        totalVerses: 123,
        revealedVerses: 0,
        translation: "Hud",
      ),
      const SurahModel(
        number: 12,
        englishName: "Yusuf",
        arabicName: "يوسف",
        revelationType: "MECCAN",
        totalVerses: 111,
        revealedVerses: 0,
        translation: "Joseph",
      ),
      const SurahModel(
        number: 13,
        englishName: "Ar-Ra'd",
        arabicName: "الرعد",
        revelationType: "MEDINAN",
        totalVerses: 43,
        revealedVerses: 0,
        translation: "The Thunder",
      ),
      const SurahModel(
        number: 14,
        englishName: "Ibrahim",
        arabicName: "ابراهيم",
        revelationType: "MECCAN",
        totalVerses: 52,
        revealedVerses: 0,
        translation: "Abraham",
      ),
      const SurahModel(
        number: 15,
        englishName: "Al-Hijr",
        arabicName: "الحجر",
        revelationType: "MECCAN",
        totalVerses: 99,
        revealedVerses: 0,
        translation: "The Rocky Tract",
      ),
      const SurahModel(
        number: 16,
        englishName: "An-Nahl",
        arabicName: "النحل",
        revelationType: "MECCAN",
        totalVerses: 128,
        revealedVerses: 0,
        translation: "The Bee",
      ),
      const SurahModel(
        number: 17,
        englishName: "Al-Isra",
        arabicName: "الإسراء",
        revelationType: "MECCAN",
        totalVerses: 111,
        revealedVerses: 0,
        translation: "The Night Journey",
      ),
      const SurahModel(
        number: 18,
        englishName: "Al-Kahf",
        arabicName: "الكهف",
        revelationType: "MECCAN",
        totalVerses: 110,
        revealedVerses: 0,
        translation: "The Cave",
      ),
      const SurahModel(
        number: 19,
        englishName: "Maryam",
        arabicName: "مريم",
        revelationType: "MECCAN",
        totalVerses: 98,
        revealedVerses: 0,
        translation: "Mary",
      ),
      const SurahModel(
        number: 20,
        englishName: "Taha",
        arabicName: "طه",
        revelationType: "MECCAN",
        totalVerses: 135,
        revealedVerses: 0,
        translation: "Ta-Ha",
      ),
      const SurahModel(
        number: 21,
        englishName: "Al-Anbya",
        arabicName: "الأنبياء",
        revelationType: "MECCAN",
        totalVerses: 112,
        revealedVerses: 0,
        translation: "The Prophets",
      ),
      const SurahModel(
        number: 22,
        englishName: "Al-Hajj",
        arabicName: "الحج",
        revelationType: "MEDINAN",
        totalVerses: 78,
        revealedVerses: 0,
        translation: "The Pilgrimage",
      ),
      const SurahModel(
        number: 23,
        englishName: "Al-Mu'minun",
        arabicName: "المؤمنون",
        revelationType: "MECCAN",
        totalVerses: 118,
        revealedVerses: 0,
        translation: "The Believers",
      ),
      const SurahModel(
        number: 24,
        englishName: "An-Nur",
        arabicName: "النور",
        revelationType: "MEDINAN",
        totalVerses: 64,
        revealedVerses: 0,
        translation: "The Light",
      ),
      const SurahModel(
        number: 25,
        englishName: "Al-Furqan",
        arabicName: "الفرقان",
        revelationType: "MECCAN",
        totalVerses: 77,
        revealedVerses: 0,
        translation: "The Criterion",
      ),
      const SurahModel(
        number: 26,
        englishName: "Ash-Shu'ara",
        arabicName: "الشعراء",
        revelationType: "MECCAN",
        totalVerses: 227,
        revealedVerses: 0,
        translation: "The Poets",
      ),
      const SurahModel(
        number: 27,
        englishName: "An-Naml",
        arabicName: "النمل",
        revelationType: "MECCAN",
        totalVerses: 93,
        revealedVerses: 0,
        translation: "The Ant",
      ),
      const SurahModel(
        number: 28,
        englishName: "Al-Qasas",
        arabicName: "القصص",
        revelationType: "MECCAN",
        totalVerses: 88,
        revealedVerses: 0,
        translation: "The Stories",
      ),
      const SurahModel(
        number: 29,
        englishName: "Al-'Ankabut",
        arabicName: "العنكبوت",
        revelationType: "MECCAN",
        totalVerses: 69,
        revealedVerses: 0,
        translation: "The Spider",
      ),
      const SurahModel(
        number: 30,
        englishName: "Ar-Rum",
        arabicName: "الروم",
        revelationType: "MECCAN",
        totalVerses: 60,
        revealedVerses: 0,
        translation: "The Romans",
      ),
      const SurahModel(
        number: 31,
        englishName: "Luqman",
        arabicName: "لقمان",
        revelationType: "MECCAN",
        totalVerses: 34,
        revealedVerses: 0,
        translation: "Luqman",
      ),
      const SurahModel(
        number: 32,
        englishName: "As-Sajdah",
        arabicName: "السجدة",
        revelationType: "MECCAN",
        totalVerses: 30,
        revealedVerses: 0,
        translation: "The Prostration",
      ),
      const SurahModel(
        number: 33,
        englishName: "Al-Ahzab",
        arabicName: "الأحزاب",
        revelationType: "MEDINAN",
        totalVerses: 73,
        revealedVerses: 0,
        translation: "The Combined Forces",
      ),
      const SurahModel(
        number: 34,
        englishName: "Saba",
        arabicName: "سبإ",
        revelationType: "MECCAN",
        totalVerses: 54,
        revealedVerses: 0,
        translation: "Sheba",
      ),
      const SurahModel(
        number: 35,
        englishName: "Fatir",
        arabicName: "فاطر",
        revelationType: "MECCAN",
        totalVerses: 45,
        revealedVerses: 0,
        translation: "Originator",
      ),
      const SurahModel(
        number: 36,
        englishName: "Ya-Sin",
        arabicName: "يس",
        revelationType: "MECCAN",
        totalVerses: 83,
        revealedVerses: 0,
        translation: "Ya Sin",
      ),
      const SurahModel(
        number: 37,
        englishName: "As-Saffat",
        arabicName: "الصافات",
        revelationType: "MECCAN",
        totalVerses: 182,
        revealedVerses: 0,
        translation: "Those who set the Ranks",
      ),
      const SurahModel(
        number: 38,
        englishName: "Sad",
        arabicName: "ص",
        revelationType: "MECCAN",
        totalVerses: 88,
        revealedVerses: 0,
        translation: "The Letter \"Saad\"",
      ),
      const SurahModel(
        number: 39,
        englishName: "Az-Zumar",
        arabicName: "الزمر",
        revelationType: "MECCAN",
        totalVerses: 75,
        revealedVerses: 0,
        translation: "The Troops",
      ),
      const SurahModel(
        number: 40,
        englishName: "Ghafir",
        arabicName: "غافر",
        revelationType: "MECCAN",
        totalVerses: 85,
        revealedVerses: 0,
        translation: "The Forgiver",
      ),
      const SurahModel(
        number: 41,
        englishName: "Fussilat",
        arabicName: "فصلت",
        revelationType: "MECCAN",
        totalVerses: 54,
        revealedVerses: 0,
        translation: "Explained in Detail",
      ),
      const SurahModel(
        number: 42,
        englishName: "Ash-Shuraa",
        arabicName: "الشورى",
        revelationType: "MECCAN",
        totalVerses: 53,
        revealedVerses: 0,
        translation: "The Consultation",
      ),
      const SurahModel(
        number: 43,
        englishName: "Az-Zukhruf",
        arabicName: "الزخرف",
        revelationType: "MECCAN",
        totalVerses: 89,
        revealedVerses: 0,
        translation: "The Ornaments of Gold",
      ),
      const SurahModel(
        number: 44,
        englishName: "Ad-Dukhan",
        arabicName: "الدخان",
        revelationType: "MECCAN",
        totalVerses: 59,
        revealedVerses: 0,
        translation: "The Smoke",
      ),
      const SurahModel(
        number: 45,
        englishName: "Al-Jathiyah",
        arabicName: "الجاثية",
        revelationType: "MECCAN",
        totalVerses: 37,
        revealedVerses: 0,
        translation: "The Crouching",
      ),
      const SurahModel(
        number: 46,
        englishName: "Al-Ahqaf",
        arabicName: "الأحقاف",
        revelationType: "MECCAN",
        totalVerses: 35,
        revealedVerses: 0,
        translation: "The Wind-Curved Sandhills",
      ),
      const SurahModel(
        number: 47,
        englishName: "Muhammad",
        arabicName: "محمد",
        revelationType: "MEDINAN",
        totalVerses: 38,
        revealedVerses: 0,
        translation: "Muhammad",
      ),
      const SurahModel(
        number: 48,
        englishName: "Al-Fath",
        arabicName: "الفتح",
        revelationType: "MEDINAN",
        totalVerses: 29,
        revealedVerses: 0,
        translation: "The Victory",
      ),
      const SurahModel(
        number: 49,
        englishName: "Al-Hujurat",
        arabicName: "الحجرات",
        revelationType: "MEDINAN",
        totalVerses: 18,
        revealedVerses: 0,
        translation: "The Rooms",
      ),
      const SurahModel(
        number: 50,
        englishName: "Qaf",
        arabicName: "ق",
        revelationType: "MECCAN",
        totalVerses: 45,
        revealedVerses: 0,
        translation: "The Letter \"Qaf\"",
      ),
      const SurahModel(
        number: 51,
        englishName: "Adh-Dhariyat",
        arabicName: "الذاريات",
        revelationType: "MECCAN",
        totalVerses: 60,
        revealedVerses: 0,
        translation: "The Winnowing Winds",
      ),
      const SurahModel(
        number: 52,
        englishName: "At-Tur",
        arabicName: "الطور",
        revelationType: "MECCAN",
        totalVerses: 49,
        revealedVerses: 0,
        translation: "The Mount",
      ),
      const SurahModel(
        number: 53,
        englishName: "An-Najm",
        arabicName: "النجم",
        revelationType: "MECCAN",
        totalVerses: 62,
        revealedVerses: 0,
        translation: "The Star",
      ),
      const SurahModel(
        number: 54,
        englishName: "Al-Qamar",
        arabicName: "القمر",
        revelationType: "MECCAN",
        totalVerses: 55,
        revealedVerses: 0,
        translation: "The Moon",
      ),
      const SurahModel(
        number: 55,
        englishName: "Ar-Rahman",
        arabicName: "الرحمن",
        revelationType: "MEDINAN",
        totalVerses: 78,
        revealedVerses: 0,
        translation: "The Beneficent",
      ),
      const SurahModel(
        number: 56,
        englishName: "Al-Waqi'ah",
        arabicName: "الواقعة",
        revelationType: "MECCAN",
        totalVerses: 96,
        revealedVerses: 0,
        translation: "The Inevitable",
      ),
      const SurahModel(
        number: 57,
        englishName: "Al-Hadid",
        arabicName: "الحديد",
        revelationType: "MEDINAN",
        totalVerses: 29,
        revealedVerses: 0,
        translation: "The Iron",
      ),
      const SurahModel(
        number: 58,
        englishName: "Al-Mujadila",
        arabicName: "المجادلة",
        revelationType: "MEDINAN",
        totalVerses: 22,
        revealedVerses: 0,
        translation: "The Pleading Woman",
      ),
      const SurahModel(
        number: 59,
        englishName: "Al-Hashr",
        arabicName: "الحشر",
        revelationType: "MEDINAN",
        totalVerses: 24,
        revealedVerses: 0,
        translation: "The Exile",
      ),
      const SurahModel(
        number: 60,
        englishName: "Al-Mumtahanah",
        arabicName: "الممتحنة",
        revelationType: "MEDINAN",
        totalVerses: 13,
        revealedVerses: 0,
        translation: "She that is to be examined",
      ),
      const SurahModel(
        number: 61,
        englishName: "As-Saf",
        arabicName: "الصف",
        revelationType: "MEDINAN",
        totalVerses: 14,
        revealedVerses: 0,
        translation: "The Ranks",
      ),
      const SurahModel(
        number: 62,
        englishName: "Al-Jumu'ah",
        arabicName: "الجمعة",
        revelationType: "MEDINAN",
        totalVerses: 11,
        revealedVerses: 0,
        translation: "The Congregation, Friday",
      ),
      const SurahModel(
        number: 63,
        englishName: "Al-Munafiqun",
        arabicName: "المنافقون",
        revelationType: "MEDINAN",
        totalVerses: 11,
        revealedVerses: 0,
        translation: "The Hypocrites",
      ),
      const SurahModel(
        number: 64,
        englishName: "At-Taghabun",
        arabicName: "التغابن",
        revelationType: "MEDINAN",
        totalVerses: 18,
        revealedVerses: 0,
        translation: "The Mutual Disillusion",
      ),
      const SurahModel(
        number: 65,
        englishName: "At-Talaq",
        arabicName: "الطلاق",
        revelationType: "MEDINAN",
        totalVerses: 12,
        revealedVerses: 0,
        translation: "The Divorce",
      ),
      const SurahModel(
        number: 66,
        englishName: "At-Tahrim",
        arabicName: "التحريم",
        revelationType: "MEDINAN",
        totalVerses: 12,
        revealedVerses: 0,
        translation: "The Prohibition",
      ),
      const SurahModel(
        number: 67,
        englishName: "Al-Mulk",
        arabicName: "الملك",
        revelationType: "MECCAN",
        totalVerses: 30,
        revealedVerses: 0,
        translation: "The Sovereignty",
      ),
      const SurahModel(
        number: 68,
        englishName: "Al-Qalam",
        arabicName: "القلم",
        revelationType: "MECCAN",
        totalVerses: 52,
        revealedVerses: 0,
        translation: "The Pen",
      ),
      const SurahModel(
        number: 69,
        englishName: "Al-Haqqah",
        arabicName: "الحاقة",
        revelationType: "MECCAN",
        totalVerses: 52,
        revealedVerses: 0,
        translation: "The Reality",
      ),
      const SurahModel(
        number: 70,
        englishName: "Al-Ma'arij",
        arabicName: "المعارج",
        revelationType: "MECCAN",
        totalVerses: 44,
        revealedVerses: 0,
        translation: "The Ascending Stairways",
      ),
      const SurahModel(
        number: 71,
        englishName: "Nuh",
        arabicName: "نوح",
        revelationType: "MECCAN",
        totalVerses: 28,
        revealedVerses: 0,
        translation: "Noah",
      ),
      const SurahModel(
        number: 72,
        englishName: "Al-Jinn",
        arabicName: "الجن",
        revelationType: "MECCAN",
        totalVerses: 28,
        revealedVerses: 0,
        translation: "The Jinn",
      ),
      const SurahModel(
        number: 73,
        englishName: "Al-Muzzammil",
        arabicName: "المزمل",
        revelationType: "MECCAN",
        totalVerses: 20,
        revealedVerses: 0,
        translation: "The Enshrouded One",
      ),
      const SurahModel(
        number: 74,
        englishName: "Al-Muddaththir",
        arabicName: "المدثر",
        revelationType: "MECCAN",
        totalVerses: 56,
        revealedVerses: 0,
        translation: "The Cloaked One",
      ),
      const SurahModel(
        number: 75,
        englishName: "Al-Qiyamah",
        arabicName: "القيامة",
        revelationType: "MECCAN",
        totalVerses: 40,
        revealedVerses: 0,
        translation: "The Resurrection",
      ),
      const SurahModel(
        number: 76,
        englishName: "Al-Insan",
        arabicName: "الانسان",
        revelationType: "MEDINAN",
        totalVerses: 31,
        revealedVerses: 0,
        translation: "The Man",
      ),
      const SurahModel(
        number: 77,
        englishName: "Al-Mursalat",
        arabicName: "المرسلات",
        revelationType: "MECCAN",
        totalVerses: 50,
        revealedVerses: 0,
        translation: "The Emissaries",
      ),
      const SurahModel(
        number: 78,
        englishName: "An-Naba",
        arabicName: "النبإ",
        revelationType: "MECCAN",
        totalVerses: 40,
        revealedVerses: 0,
        translation: "The Tidings",
      ),
      const SurahModel(
        number: 79,
        englishName: "An-Nazi'at",
        arabicName: "النازعات",
        revelationType: "MECCAN",
        totalVerses: 46,
        revealedVerses: 0,
        translation: "Those who drag forth",
      ),
      const SurahModel(
        number: 80,
        englishName: "'Abasa",
        arabicName: "عبس",
        revelationType: "MECCAN",
        totalVerses: 42,
        revealedVerses: 0,
        translation: "He Frowned",
      ),
      const SurahModel(
        number: 81,
        englishName: "At-Takwir",
        arabicName: "التكوير",
        revelationType: "MECCAN",
        totalVerses: 29,
        revealedVerses: 0,
        translation: "The Overthrowing",
      ),
      const SurahModel(
        number: 82,
        englishName: "Al-Infitar",
        arabicName: "الإنفطار",
        revelationType: "MECCAN",
        totalVerses: 19,
        revealedVerses: 0,
        translation: "The Cleaving",
      ),
      const SurahModel(
        number: 83,
        englishName: "Al-Mutaffifin",
        arabicName: "المطففين",
        revelationType: "MECCAN",
        totalVerses: 36,
        revealedVerses: 0,
        translation: "The Defrauding",
      ),
      const SurahModel(
        number: 84,
        englishName: "Al-Inshiqaq",
        arabicName: "الإنشقاق",
        revelationType: "MECCAN",
        totalVerses: 25,
        revealedVerses: 0,
        translation: "The Sundering",
      ),
      const SurahModel(
        number: 85,
        englishName: "Al-Buruj",
        arabicName: "البروج",
        revelationType: "MECCAN",
        totalVerses: 22,
        revealedVerses: 0,
        translation: "The Mansions of the Stars",
      ),
      const SurahModel(
        number: 86,
        englishName: "At-Tariq",
        arabicName: "الطارق",
        revelationType: "MECCAN",
        totalVerses: 17,
        revealedVerses: 0,
        translation: "The Nightcommer",
      ),
      const SurahModel(
        number: 87,
        englishName: "Al-A'la",
        arabicName: "الأعلى",
        revelationType: "MECCAN",
        totalVerses: 19,
        revealedVerses: 0,
        translation: "The Most High",
      ),
      const SurahModel(
        number: 88,
        englishName: "Al-Ghashiyah",
        arabicName: "الغاشية",
        revelationType: "MECCAN",
        totalVerses: 26,
        revealedVerses: 0,
        translation: "The Overwhelming",
      ),
      const SurahModel(
        number: 89,
        englishName: "Al-Fajr",
        arabicName: "الفجر",
        revelationType: "MECCAN",
        totalVerses: 30,
        revealedVerses: 0,
        translation: "The Dawn",
      ),
      const SurahModel(
        number: 90,
        englishName: "Al-Balad",
        arabicName: "البلد",
        revelationType: "MECCAN",
        totalVerses: 20,
        revealedVerses: 0,
        translation: "The City",
      ),
      const SurahModel(
        number: 91,
        englishName: "Ash-Shams",
        arabicName: "الشمس",
        revelationType: "MECCAN",
        totalVerses: 15,
        revealedVerses: 0,
        translation: "The Sun",
      ),
      const SurahModel(
        number: 92,
        englishName: "Al-Layl",
        arabicName: "الليل",
        revelationType: "MECCAN",
        totalVerses: 21,
        revealedVerses: 0,
        translation: "The Night",
      ),
      const SurahModel(
        number: 93,
        englishName: "Ad-Duhaa",
        arabicName: "الضحى",
        revelationType: "MECCAN",
        totalVerses: 11,
        revealedVerses: 0,
        translation: "The Morning Hours",
      ),
      const SurahModel(
        number: 94,
        englishName: "Ash-Sharh",
        arabicName: "الشرح",
        revelationType: "MECCAN",
        totalVerses: 8,
        revealedVerses: 0,
        translation: "The Relief",
      ),
      const SurahModel(
        number: 95,
        englishName: "At-Tin",
        arabicName: "التين",
        revelationType: "MECCAN",
        totalVerses: 8,
        revealedVerses: 0,
        translation: "The Fig",
      ),
      const SurahModel(
        number: 96,
        englishName: "Al-'Alaq",
        arabicName: "العلق",
        revelationType: "MECCAN",
        totalVerses: 19,
        revealedVerses: 0,
        translation: "The Clot",
      ),
      const SurahModel(
        number: 97,
        englishName: "Al-Qadr",
        arabicName: "القدر",
        revelationType: "MECCAN",
        totalVerses: 5,
        revealedVerses: 0,
        translation: "The Power",
      ),
      const SurahModel(
        number: 98,
        englishName: "Al-Bayyinah",
        arabicName: "البينة",
        revelationType: "MEDINAN",
        totalVerses: 8,
        revealedVerses: 0,
        translation: "The Clear Proof",
      ),
      const SurahModel(
        number: 99,
        englishName: "Az-Zalzalah",
        arabicName: "الزلزلة",
        revelationType: "MEDINAN",
        totalVerses: 8,
        revealedVerses: 0,
        translation: "The Earthquake",
      ),
      const SurahModel(
        number: 100,
        englishName: "Al-'Adiyat",
        arabicName: "العاديات",
        revelationType: "MECCAN",
        totalVerses: 11,
        revealedVerses: 0,
        translation: "The Courser",
      ),
      const SurahModel(
        number: 101,
        englishName: "Al-Qari'ah",
        arabicName: "القارعة",
        revelationType: "MECCAN",
        totalVerses: 11,
        revealedVerses: 0,
        translation: "The Calamity",
      ),
      const SurahModel(
        number: 102,
        englishName: "At-Takathur",
        arabicName: "التكاثر",
        revelationType: "MECCAN",
        totalVerses: 8,
        revealedVerses: 0,
        translation: "The Rivalry in world increase",
      ),
      const SurahModel(
        number: 103,
        englishName: "Al-'Asr",
        arabicName: "العصر",
        revelationType: "MECCAN",
        totalVerses: 3,
        revealedVerses: 0,
        translation: "The Declining Day",
      ),
      const SurahModel(
        number: 104,
        englishName: "Al-Humazah",
        arabicName: "الهمزة",
        revelationType: "MECCAN",
        totalVerses: 9,
        revealedVerses: 0,
        translation: "The Traducer",
      ),
      const SurahModel(
        number: 105,
        englishName: "Al-Fil",
        arabicName: "الفيل",
        revelationType: "MECCAN",
        totalVerses: 5,
        revealedVerses: 0,
        translation: "The Elephant",
      ),
      const SurahModel(
        number: 106,
        englishName: "Quraysh",
        arabicName: "قريش",
        revelationType: "MECCAN",
        totalVerses: 4,
        revealedVerses: 0,
        translation: "Quraysh",
      ),
      const SurahModel(
        number: 107,
        englishName: "Al-Ma'un",
        arabicName: "الماعون",
        revelationType: "MECCAN",
        totalVerses: 7,
        revealedVerses: 0,
        translation: "The Small kindnesses",
      ),
      const SurahModel(
        number: 108,
        englishName: "Al-Kawthar",
        arabicName: "الكوثر",
        revelationType: "MECCAN",
        totalVerses: 3,
        revealedVerses: 0,
        translation: "The Abundance",
      ),
      const SurahModel(
        number: 109,
        englishName: "Al-Kafirun",
        arabicName: "الكافرون",
        revelationType: "MECCAN",
        totalVerses: 6,
        revealedVerses: 0,
        translation: "The Disbelievers",
      ),
      const SurahModel(
        number: 110,
        englishName: "An-Nasr",
        arabicName: "النصر",
        revelationType: "MEDINAN",
        totalVerses: 3,
        revealedVerses: 0,
        translation: "The Divine Support",
      ),
      const SurahModel(
        number: 111,
        englishName: "Al-Masad",
        arabicName: "المسد",
        revelationType: "MECCAN",
        totalVerses: 5,
        revealedVerses: 0,
        translation: "The Palm Fiber",
      ),
      const SurahModel(
        number: 112,
        englishName: "Al-Ikhlas",
        arabicName: "الإخلاص",
        revelationType: "MECCAN",
        totalVerses: 4,
        revealedVerses: 0,
        translation: "The Sincerity",
      ),
      const SurahModel(
        number: 113,
        englishName: "Al-Falaq",
        arabicName: "الفلق",
        revelationType: "MECCAN",
        totalVerses: 5,
        revealedVerses: 0,
        translation: "The Daybreak",
      ),
      const SurahModel(
        number: 114,
        englishName: "An-Nas",
        arabicName: "الناس",
        revelationType: "MECCAN",
        totalVerses: 6,
        revealedVerses: 0,
        translation: "Mankind",
      ),
    ];
  }
}
