import '../../feature/home/model/surah_model.dart';

class StaticJuzData {
  static List<JuzModel> getAllJuz() {
    return [
      const JuzModel(
        number: 1,
        surahs: [
          JuzSurahModel(
            number: 1,
            englishName: "Al-Fatihah",
            arabicName: "الفاتحة",
            revelationType: "MECCAN",
            versesRange: "7 VERSES",
            totalVerses: 7,
            translation: "The Opener",
            juzId: 1,
          ),
          JuzSurahModel(
            number: 2,
            englishName: "Al-Baqarah",
            arabicName: "البقرة",
            revelationType: "MEDINAN",
            versesRange: "286 VERSES",
            totalVerses: 286,
            translation: "The Cow",
            juzId: 1,
          ),
        ],
      ),
      const JuzModel(
        number: 2,
        surahs: [
          JuzSurahModel(
            number: 2,
            englishName: "Al-Baqarah",
            arabicName: "البقرة",
            revelationType: "MEDINAN",
            versesRange: "286 VERSES",
            totalVerses: 286,
            translation: "The Cow",
            juzId: 2,
          ),
        ],
      ),
      const JuzModel(
        number: 3,
        surahs: [
          JuzSurahModel(
            number: 2,
            englishName: "Al-Baqarah",
            arabicName: "البقرة",
            revelationType: "MEDINAN",
            versesRange: "286 VERSES",
            totalVerses: 286,
            translation: "The Cow",
            juzId: 3,
          ),
          JuzSurahModel(
            number: 3,
            englishName: "Ali 'Imran",
            arabicName: "آل عمران",
            revelationType: "MEDINAN",
            versesRange: "200 VERSES",
            totalVerses: 200,
            translation: "Family of Imran",
            juzId: 3,
          ),
        ],
      ),
      const JuzModel(
        number: 4,
        surahs: [
          JuzSurahModel(
            number: 3,
            englishName: "Ali 'Imran",
            arabicName: "آل عمران",
            revelationType: "MEDINAN",
            versesRange: "200 VERSES",
            totalVerses: 200,
            translation: "Family of Imran",
            juzId: 4,
          ),
          JuzSurahModel(
            number: 4,
            englishName: "An-Nisa",
            arabicName: "النساء",
            revelationType: "MEDINAN",
            versesRange: "176 VERSES",
            totalVerses: 176,
            translation: "The Women",
            juzId: 4,
          ),
        ],
      ),
      const JuzModel(
        number: 5,
        surahs: [
          JuzSurahModel(
            number: 4,
            englishName: "An-Nisa",
            arabicName: "النساء",
            revelationType: "MEDINAN",
            versesRange: "176 VERSES",
            totalVerses: 176,
            translation: "The Women",
            juzId: 5,
          ),
        ],
      ),
      const JuzModel(
        number: 6,
        surahs: [
          JuzSurahModel(
            number: 4,
            englishName: "An-Nisa",
            arabicName: "النساء",
            revelationType: "MEDINAN",
            versesRange: "176 VERSES",
            totalVerses: 176,
            translation: "The Women",
            juzId: 6,
          ),
          JuzSurahModel(
            number: 5,
            englishName: "Al-Ma'idah",
            arabicName: "المائدة",
            revelationType: "MEDINAN",
            versesRange: "120 VERSES",
            totalVerses: 120,
            translation: "The Table Spread",
            juzId: 6,
          ),
        ],
      ),
      const JuzModel(
        number: 7,
        surahs: [
          JuzSurahModel(
            number: 5,
            englishName: "Al-Ma'idah",
            arabicName: "المائدة",
            revelationType: "MEDINAN",
            versesRange: "120 VERSES",
            totalVerses: 120,
            translation: "The Table Spread",
            juzId: 7,
          ),
          JuzSurahModel(
            number: 6,
            englishName: "Al-An'am",
            arabicName: "الأنعام",
            revelationType: "MECCAN",
            versesRange: "165 VERSES",
            totalVerses: 165,
            translation: "The Cattle",
            juzId: 7,
          ),
        ],
      ),
      const JuzModel(
        number: 8,
        surahs: [
          JuzSurahModel(
            number: 6,
            englishName: "Al-An'am",
            arabicName: "الأنعام",
            revelationType: "MECCAN",
            versesRange: "165 VERSES",
            totalVerses: 165,
            translation: "The Cattle",
            juzId: 8,
          ),
          JuzSurahModel(
            number: 7,
            englishName: "Al-A'raf",
            arabicName: "الأعراف",
            revelationType: "MECCAN",
            versesRange: "206 VERSES",
            totalVerses: 206,
            translation: "The Heights",
            juzId: 8,
          ),
        ],
      ),
      const JuzModel(
        number: 9,
        surahs: [
          JuzSurahModel(
            number: 7,
            englishName: "Al-A'raf",
            arabicName: "الأعراف",
            revelationType: "MECCAN",
            versesRange: "206 VERSES",
            totalVerses: 206,
            translation: "The Heights",
            juzId: 9,
          ),
          JuzSurahModel(
            number: 8,
            englishName: "Al-Anfal",
            arabicName: "الأنفال",
            revelationType: "MEDINAN",
            versesRange: "75 VERSES",
            totalVerses: 75,
            translation: "The Spoils of War",
            juzId: 9,
          ),
        ],
      ),
      const JuzModel(
        number: 10,
        surahs: [
          JuzSurahModel(
            number: 8,
            englishName: "Al-Anfal",
            arabicName: "الأنفال",
            revelationType: "MEDINAN",
            versesRange: "75 VERSES",
            totalVerses: 75,
            translation: "The Spoils of War",
            juzId: 10,
          ),
          JuzSurahModel(
            number: 9,
            englishName: "At-Tawbah",
            arabicName: "التوبة",
            revelationType: "MEDINAN",
            versesRange: "129 VERSES",
            totalVerses: 129,
            translation: "The Repentance",
            juzId: 10,
          ),
        ],
      ),
      const JuzModel(
        number: 11,
        surahs: [
          JuzSurahModel(
            number: 9,
            englishName: "At-Tawbah",
            arabicName: "التوبة",
            revelationType: "MEDINAN",
            versesRange: "129 VERSES",
            totalVerses: 129,
            translation: "The Repentance",
            juzId: 11,
          ),
          JuzSurahModel(
            number: 10,
            englishName: "Yunus",
            arabicName: "يونس",
            revelationType: "MECCAN",
            versesRange: "109 VERSES",
            totalVerses: 109,
            translation: "Jonah",
            juzId: 11,
          ),
          JuzSurahModel(
            number: 11,
            englishName: "Hud",
            arabicName: "هود",
            revelationType: "MECCAN",
            versesRange: "123 VERSES",
            totalVerses: 123,
            translation: "Hud",
            juzId: 11,
          ),
        ],
      ),
      const JuzModel(
        number: 12,
        surahs: [
          JuzSurahModel(
            number: 11,
            englishName: "Hud",
            arabicName: "هود",
            revelationType: "MECCAN",
            versesRange: "123 VERSES",
            totalVerses: 123,
            translation: "Hud",
            juzId: 12,
          ),
          JuzSurahModel(
            number: 12,
            englishName: "Yusuf",
            arabicName: "يوسف",
            revelationType: "MECCAN",
            versesRange: "111 VERSES",
            totalVerses: 111,
            translation: "Joseph",
            juzId: 12,
          ),
        ],
      ),
      const JuzModel(
        number: 13,
        surahs: [
          JuzSurahModel(
            number: 12,
            englishName: "Yusuf",
            arabicName: "يوسف",
            revelationType: "MECCAN",
            versesRange: "111 VERSES",
            totalVerses: 111,
            translation: "Joseph",
            juzId: 13,
          ),
          JuzSurahModel(
            number: 13,
            englishName: "Ar-Ra'd",
            arabicName: "الرعد",
            revelationType: "MEDINAN",
            versesRange: "43 VERSES",
            totalVerses: 43,
            translation: "The Thunder",
            juzId: 13,
          ),
          JuzSurahModel(
            number: 14,
            englishName: "Ibrahim",
            arabicName: "ابراهيم",
            revelationType: "MECCAN",
            versesRange: "52 VERSES",
            totalVerses: 52,
            translation: "Abraham",
            juzId: 13,
          ),
        ],
      ),
      const JuzModel(
        number: 14,
        surahs: [
          JuzSurahModel(
            number: 15,
            englishName: "Al-Hijr",
            arabicName: "الحجر",
            revelationType: "MECCAN",
            versesRange: "99 VERSES",
            totalVerses: 99,
            translation: "The Rocky Tract",
            juzId: 14,
          ),
          JuzSurahModel(
            number: 16,
            englishName: "An-Nahl",
            arabicName: "النحل",
            revelationType: "MECCAN",
            versesRange: "128 VERSES",
            totalVerses: 128,
            translation: "The Bee",
            juzId: 14,
          ),
        ],
      ),
      const JuzModel(
        number: 15,
        surahs: [
          JuzSurahModel(
            number: 17,
            englishName: "Al-Isra",
            arabicName: "الإسراء",
            revelationType: "MECCAN",
            versesRange: "111 VERSES",
            totalVerses: 111,
            translation: "The Night Journey",
            juzId: 15,
          ),
          JuzSurahModel(
            number: 18,
            englishName: "Al-Kahf",
            arabicName: "الكهف",
            revelationType: "MECCAN",
            versesRange: "110 VERSES",
            totalVerses: 110,
            translation: "The Cave",
            juzId: 15,
          ),
        ],
      ),
      const JuzModel(
        number: 16,
        surahs: [
          JuzSurahModel(
            number: 18,
            englishName: "Al-Kahf",
            arabicName: "الكهف",
            revelationType: "MECCAN",
            versesRange: "110 VERSES",
            totalVerses: 110,
            translation: "The Cave",
            juzId: 16,
          ),
          JuzSurahModel(
            number: 19,
            englishName: "Maryam",
            arabicName: "مريم",
            revelationType: "MECCAN",
            versesRange: "98 VERSES",
            totalVerses: 98,
            translation: "Mary",
            juzId: 16,
          ),
          JuzSurahModel(
            number: 20,
            englishName: "Taha",
            arabicName: "طه",
            revelationType: "MECCAN",
            versesRange: "135 VERSES",
            totalVerses: 135,
            translation: "Ta-Ha",
            juzId: 16,
          ),
        ],
      ),
      const JuzModel(
        number: 17,
        surahs: [
          JuzSurahModel(
            number: 21,
            englishName: "Al-Anbya",
            arabicName: "الأنبياء",
            revelationType: "MECCAN",
            versesRange: "112 VERSES",
            totalVerses: 112,
            translation: "The Prophets",
            juzId: 17,
          ),
          JuzSurahModel(
            number: 22,
            englishName: "Al-Hajj",
            arabicName: "الحج",
            revelationType: "MEDINAN",
            versesRange: "78 VERSES",
            totalVerses: 78,
            translation: "The Pilgrimage",
            juzId: 17,
          ),
        ],
      ),
      const JuzModel(
        number: 18,
        surahs: [
          JuzSurahModel(
            number: 23,
            englishName: "Al-Mu'minun",
            arabicName: "المؤمنون",
            revelationType: "MECCAN",
            versesRange: "118 VERSES",
            totalVerses: 118,
            translation: "The Believers",
            juzId: 18,
          ),
          JuzSurahModel(
            number: 24,
            englishName: "An-Nur",
            arabicName: "النور",
            revelationType: "MEDINAN",
            versesRange: "64 VERSES",
            totalVerses: 64,
            translation: "The Light",
            juzId: 18,
          ),
          JuzSurahModel(
            number: 25,
            englishName: "Al-Furqan",
            arabicName: "الفرقان",
            revelationType: "MECCAN",
            versesRange: "77 VERSES",
            totalVerses: 77,
            translation: "The Criterion",
            juzId: 18,
          ),
        ],
      ),
      const JuzModel(
        number: 19,
        surahs: [
          JuzSurahModel(
            number: 25,
            englishName: "Al-Furqan",
            arabicName: "الفرقان",
            revelationType: "MECCAN",
            versesRange: "77 VERSES",
            totalVerses: 77,
            translation: "The Criterion",
            juzId: 19,
          ),
          JuzSurahModel(
            number: 26,
            englishName: "Ash-Shu'ara",
            arabicName: "الشعراء",
            revelationType: "MECCAN",
            versesRange: "227 VERSES",
            totalVerses: 227,
            translation: "The Poets",
            juzId: 19,
          ),
          JuzSurahModel(
            number: 27,
            englishName: "An-Naml",
            arabicName: "النمل",
            revelationType: "MECCAN",
            versesRange: "93 VERSES",
            totalVerses: 93,
            translation: "The Ant",
            juzId: 19,
          ),
        ],
      ),
      const JuzModel(
        number: 20,
        surahs: [
          JuzSurahModel(
            number: 27,
            englishName: "An-Naml",
            arabicName: "النمل",
            revelationType: "MECCAN",
            versesRange: "93 VERSES",
            totalVerses: 93,
            translation: "The Ant",
            juzId: 20,
          ),
          JuzSurahModel(
            number: 28,
            englishName: "Al-Qasas",
            arabicName: "القصص",
            revelationType: "MECCAN",
            versesRange: "88 VERSES",
            totalVerses: 88,
            translation: "The Stories",
            juzId: 20,
          ),
          JuzSurahModel(
            number: 29,
            englishName: "Al-'Ankabut",
            arabicName: "العنكبوت",
            revelationType: "MECCAN",
            versesRange: "69 VERSES",
            totalVerses: 69,
            translation: "The Spider",
            juzId: 20,
          ),
        ],
      ),
      const JuzModel(
        number: 21,
        surahs: [
          JuzSurahModel(
            number: 29,
            englishName: "Al-'Ankabut",
            arabicName: "العنكبوت",
            revelationType: "MECCAN",
            versesRange: "69 VERSES",
            totalVerses: 69,
            translation: "The Spider",
            juzId: 21,
          ),
          JuzSurahModel(
            number: 30,
            englishName: "Ar-Rum",
            arabicName: "الروم",
            revelationType: "MECCAN",
            versesRange: "60 VERSES",
            totalVerses: 60,
            translation: "The Romans",
            juzId: 21,
          ),
          JuzSurahModel(
            number: 31,
            englishName: "Luqman",
            arabicName: "لقمان",
            revelationType: "MECCAN",
            versesRange: "34 VERSES",
            totalVerses: 34,
            translation: "Luqman",
            juzId: 21,
          ),
          JuzSurahModel(
            number: 32,
            englishName: "As-Sajdah",
            arabicName: "السجدة",
            revelationType: "MECCAN",
            versesRange: "30 VERSES",
            totalVerses: 30,
            translation: "The Prostration",
            juzId: 21,
          ),
          JuzSurahModel(
            number: 33,
            englishName: "Al-Ahzab",
            arabicName: "الأحزاب",
            revelationType: "MEDINAN",
            versesRange: "73 VERSES",
            totalVerses: 73,
            translation: "The Combined Forces",
            juzId: 21,
          ),
        ],
      ),
      const JuzModel(
        number: 22,
        surahs: [
          JuzSurahModel(
            number: 33,
            englishName: "Al-Ahzab",
            arabicName: "الأحزاب",
            revelationType: "MEDINAN",
            versesRange: "73 VERSES",
            totalVerses: 73,
            translation: "The Combined Forces",
            juzId: 22,
          ),
          JuzSurahModel(
            number: 34,
            englishName: "Saba",
            arabicName: "سبإ",
            revelationType: "MECCAN",
            versesRange: "54 VERSES",
            totalVerses: 54,
            translation: "Sheba",
            juzId: 22,
          ),
          JuzSurahModel(
            number: 35,
            englishName: "Fatir",
            arabicName: "فاطر",
            revelationType: "MECCAN",
            versesRange: "45 VERSES",
            totalVerses: 45,
            translation: "Originator",
            juzId: 22,
          ),
          JuzSurahModel(
            number: 36,
            englishName: "Ya-Sin",
            arabicName: "يس",
            revelationType: "MECCAN",
            versesRange: "83 VERSES",
            totalVerses: 83,
            translation: "Ya Sin",
            juzId: 22,
          ),
        ],
      ),
      const JuzModel(
        number: 23,
        surahs: [
          JuzSurahModel(
            number: 36,
            englishName: "Ya-Sin",
            arabicName: "يس",
            revelationType: "MECCAN",
            versesRange: "83 VERSES",
            totalVerses: 83,
            translation: "Ya Sin",
            juzId: 23,
          ),
          JuzSurahModel(
            number: 37,
            englishName: "As-Saffat",
            arabicName: "الصافات",
            revelationType: "MECCAN",
            versesRange: "182 VERSES",
            totalVerses: 182,
            translation: "Those who set the Ranks",
            juzId: 23,
          ),
          JuzSurahModel(
            number: 38,
            englishName: "Sad",
            arabicName: "ص",
            revelationType: "MECCAN",
            versesRange: "88 VERSES",
            totalVerses: 88,
            translation: "The Letter \"Saad\"",
            juzId: 23,
          ),
          JuzSurahModel(
            number: 39,
            englishName: "Az-Zumar",
            arabicName: "الزمر",
            revelationType: "MECCAN",
            versesRange: "75 VERSES",
            totalVerses: 75,
            translation: "The Troops",
            juzId: 23,
          ),
        ],
      ),
      const JuzModel(
        number: 24,
        surahs: [
          JuzSurahModel(
            number: 39,
            englishName: "Az-Zumar",
            arabicName: "الزمر",
            revelationType: "MECCAN",
            versesRange: "75 VERSES",
            totalVerses: 75,
            translation: "The Troops",
            juzId: 24,
          ),
          JuzSurahModel(
            number: 40,
            englishName: "Ghafir",
            arabicName: "غافر",
            revelationType: "MECCAN",
            versesRange: "85 VERSES",
            totalVerses: 85,
            translation: "The Forgiver",
            juzId: 24,
          ),
          JuzSurahModel(
            number: 41,
            englishName: "Fussilat",
            arabicName: "فصلت",
            revelationType: "MECCAN",
            versesRange: "54 VERSES",
            totalVerses: 54,
            translation: "Explained in Detail",
            juzId: 24,
          ),
        ],
      ),
      const JuzModel(
        number: 25,
        surahs: [
          JuzSurahModel(
            number: 41,
            englishName: "Fussilat",
            arabicName: "فصلت",
            revelationType: "MECCAN",
            versesRange: "54 VERSES",
            totalVerses: 54,
            translation: "Explained in Detail",
            juzId: 25,
          ),
          JuzSurahModel(
            number: 42,
            englishName: "Ash-Shuraa",
            arabicName: "الشورى",
            revelationType: "MECCAN",
            versesRange: "53 VERSES",
            totalVerses: 53,
            translation: "The Consultation",
            juzId: 25,
          ),
          JuzSurahModel(
            number: 43,
            englishName: "Az-Zukhruf",
            arabicName: "الزخرف",
            revelationType: "MECCAN",
            versesRange: "89 VERSES",
            totalVerses: 89,
            translation: "The Ornaments of Gold",
            juzId: 25,
          ),
          JuzSurahModel(
            number: 44,
            englishName: "Ad-Dukhan",
            arabicName: "الدخان",
            revelationType: "MECCAN",
            versesRange: "59 VERSES",
            totalVerses: 59,
            translation: "The Smoke",
            juzId: 25,
          ),
          JuzSurahModel(
            number: 45,
            englishName: "Al-Jathiyah",
            arabicName: "الجاثية",
            revelationType: "MECCAN",
            versesRange: "37 VERSES",
            totalVerses: 37,
            translation: "The Crouching",
            juzId: 25,
          ),
        ],
      ),
      const JuzModel(
        number: 26,
        surahs: [
          JuzSurahModel(
            number: 46,
            englishName: "Al-Ahqaf",
            arabicName: "الأحقاف",
            revelationType: "MECCAN",
            versesRange: "35 VERSES",
            totalVerses: 35,
            translation: "The Wind-Curved Sandhills",
            juzId: 26,
          ),
          JuzSurahModel(
            number: 47,
            englishName: "Muhammad",
            arabicName: "محمد",
            revelationType: "MEDINAN",
            versesRange: "38 VERSES",
            totalVerses: 38,
            translation: "Muhammad",
            juzId: 26,
          ),
          JuzSurahModel(
            number: 48,
            englishName: "Al-Fath",
            arabicName: "الفتح",
            revelationType: "MEDINAN",
            versesRange: "29 VERSES",
            totalVerses: 29,
            translation: "The Victory",
            juzId: 26,
          ),
          JuzSurahModel(
            number: 49,
            englishName: "Al-Hujurat",
            arabicName: "الحجرات",
            revelationType: "MEDINAN",
            versesRange: "18 VERSES",
            totalVerses: 18,
            translation: "The Rooms",
            juzId: 26,
          ),
          JuzSurahModel(
            number: 50,
            englishName: "Qaf",
            arabicName: "ق",
            revelationType: "MECCAN",
            versesRange: "45 VERSES",
            totalVerses: 45,
            translation: "The Letter \"Qaf\"",
            juzId: 26,
          ),
          JuzSurahModel(
            number: 51,
            englishName: "Adh-Dhariyat",
            arabicName: "الذاريات",
            revelationType: "MECCAN",
            versesRange: "60 VERSES",
            totalVerses: 60,
            translation: "The Winnowing Winds",
            juzId: 26,
          ),
        ],
      ),
      const JuzModel(
        number: 27,
        surahs: [
          JuzSurahModel(
            number: 51,
            englishName: "Adh-Dhariyat",
            arabicName: "الذاريات",
            revelationType: "MECCAN",
            versesRange: "60 VERSES",
            totalVerses: 60,
            translation: "The Winnowing Winds",
            juzId: 27,
          ),
          JuzSurahModel(
            number: 52,
            englishName: "At-Tur",
            arabicName: "الطور",
            revelationType: "MECCAN",
            versesRange: "49 VERSES",
            totalVerses: 49,
            translation: "The Mount",
            juzId: 27,
          ),
          JuzSurahModel(
            number: 53,
            englishName: "An-Najm",
            arabicName: "النجم",
            revelationType: "MECCAN",
            versesRange: "62 VERSES",
            totalVerses: 62,
            translation: "The Star",
            juzId: 27,
          ),
          JuzSurahModel(
            number: 54,
            englishName: "Al-Qamar",
            arabicName: "القمر",
            revelationType: "MECCAN",
            versesRange: "55 VERSES",
            totalVerses: 55,
            translation: "The Moon",
            juzId: 27,
          ),
          JuzSurahModel(
            number: 55,
            englishName: "Ar-Rahman",
            arabicName: "الرحمن",
            revelationType: "MEDINAN",
            versesRange: "78 VERSES",
            totalVerses: 78,
            translation: "The Beneficent",
            juzId: 27,
          ),
          JuzSurahModel(
            number: 56,
            englishName: "Al-Waqi'ah",
            arabicName: "الواقعة",
            revelationType: "MECCAN",
            versesRange: "96 VERSES",
            totalVerses: 96,
            translation: "The Inevitable",
            juzId: 27,
          ),
          JuzSurahModel(
            number: 57,
            englishName: "Al-Hadid",
            arabicName: "الحديد",
            revelationType: "MEDINAN",
            versesRange: "29 VERSES",
            totalVerses: 29,
            translation: "The Iron",
            juzId: 27,
          ),
        ],
      ),
      const JuzModel(
        number: 28,
        surahs: [
          JuzSurahModel(
            number: 58,
            englishName: "Al-Mujadila",
            arabicName: "المجادلة",
            revelationType: "MEDINAN",
            versesRange: "22 VERSES",
            totalVerses: 22,
            translation: "The Pleading Woman",
            juzId: 28,
          ),
          JuzSurahModel(
            number: 59,
            englishName: "Al-Hashr",
            arabicName: "الحشر",
            revelationType: "MEDINAN",
            versesRange: "24 VERSES",
            totalVerses: 24,
            translation: "The Exile",
            juzId: 28,
          ),
          JuzSurahModel(
            number: 60,
            englishName: "Al-Mumtahanah",
            arabicName: "الممتحنة",
            revelationType: "MEDINAN",
            versesRange: "13 VERSES",
            totalVerses: 13,
            translation: "She that is to be examined",
            juzId: 28,
          ),
          JuzSurahModel(
            number: 61,
            englishName: "As-Saf",
            arabicName: "الصف",
            revelationType: "MEDINAN",
            versesRange: "14 VERSES",
            totalVerses: 14,
            translation: "The Ranks",
            juzId: 28,
          ),
          JuzSurahModel(
            number: 62,
            englishName: "Al-Jumu'ah",
            arabicName: "الجمعة",
            revelationType: "MEDINAN",
            versesRange: "11 VERSES",
            totalVerses: 11,
            translation: "The Congregation, Friday",
            juzId: 28,
          ),
          JuzSurahModel(
            number: 63,
            englishName: "Al-Munafiqun",
            arabicName: "المنافقون",
            revelationType: "MEDINAN",
            versesRange: "11 VERSES",
            totalVerses: 11,
            translation: "The Hypocrites",
            juzId: 28,
          ),
          JuzSurahModel(
            number: 64,
            englishName: "At-Taghabun",
            arabicName: "التغابن",
            revelationType: "MEDINAN",
            versesRange: "18 VERSES",
            totalVerses: 18,
            translation: "The Mutual Disillusion",
            juzId: 28,
          ),
          JuzSurahModel(
            number: 65,
            englishName: "At-Talaq",
            arabicName: "الطلاق",
            revelationType: "MEDINAN",
            versesRange: "12 VERSES",
            totalVerses: 12,
            translation: "The Divorce",
            juzId: 28,
          ),
          JuzSurahModel(
            number: 66,
            englishName: "At-Tahrim",
            arabicName: "التحريم",
            revelationType: "MEDINAN",
            versesRange: "12 VERSES",
            totalVerses: 12,
            translation: "The Prohibition",
            juzId: 28,
          ),
        ],
      ),
      const JuzModel(
        number: 29,
        surahs: [
          JuzSurahModel(
            number: 67,
            englishName: "Al-Mulk",
            arabicName: "الملك",
            revelationType: "MECCAN",
            versesRange: "30 VERSES",
            totalVerses: 30,
            translation: "The Sovereignty",
            juzId: 29,
          ),
          JuzSurahModel(
            number: 68,
            englishName: "Al-Qalam",
            arabicName: "القلم",
            revelationType: "MECCAN",
            versesRange: "52 VERSES",
            totalVerses: 52,
            translation: "The Pen",
            juzId: 29,
          ),
          JuzSurahModel(
            number: 69,
            englishName: "Al-Haqqah",
            arabicName: "الحاقة",
            revelationType: "MECCAN",
            versesRange: "52 VERSES",
            totalVerses: 52,
            translation: "The Reality",
            juzId: 29,
          ),
          JuzSurahModel(
            number: 70,
            englishName: "Al-Ma'arij",
            arabicName: "المعارج",
            revelationType: "MECCAN",
            versesRange: "44 VERSES",
            totalVerses: 44,
            translation: "The Ascending Stairways",
            juzId: 29,
          ),
          JuzSurahModel(
            number: 71,
            englishName: "Nuh",
            arabicName: "نوح",
            revelationType: "MECCAN",
            versesRange: "28 VERSES",
            totalVerses: 28,
            translation: "Noah",
            juzId: 29,
          ),
          JuzSurahModel(
            number: 72,
            englishName: "Al-Jinn",
            arabicName: "الجن",
            revelationType: "MECCAN",
            versesRange: "28 VERSES",
            totalVerses: 28,
            translation: "The Jinn",
            juzId: 29,
          ),
          JuzSurahModel(
            number: 73,
            englishName: "Al-Muzzammil",
            arabicName: "المزمل",
            revelationType: "MECCAN",
            versesRange: "20 VERSES",
            totalVerses: 20,
            translation: "The Enshrouded One",
            juzId: 29,
          ),
          JuzSurahModel(
            number: 74,
            englishName: "Al-Muddaththir",
            arabicName: "المدثر",
            revelationType: "MECCAN",
            versesRange: "56 VERSES",
            totalVerses: 56,
            translation: "The Cloaked One",
            juzId: 29,
          ),
          JuzSurahModel(
            number: 75,
            englishName: "Al-Qiyamah",
            arabicName: "القيامة",
            revelationType: "MECCAN",
            versesRange: "40 VERSES",
            totalVerses: 40,
            translation: "The Resurrection",
            juzId: 29,
          ),
          JuzSurahModel(
            number: 76,
            englishName: "Al-Insan",
            arabicName: "الانسان",
            revelationType: "MEDINAN",
            versesRange: "31 VERSES",
            totalVerses: 31,
            translation: "The Man",
            juzId: 29,
          ),
          JuzSurahModel(
            number: 77,
            englishName: "Al-Mursalat",
            arabicName: "المرسلات",
            revelationType: "MECCAN",
            versesRange: "50 VERSES",
            totalVerses: 50,
            translation: "The Emissaries",
            juzId: 29,
          ),
        ],
      ),
      const JuzModel(
        number: 30,
        surahs: [
          JuzSurahModel(
            number: 78,
            englishName: "An-Naba",
            arabicName: "النبإ",
            revelationType: "MECCAN",
            versesRange: "40 VERSES",
            totalVerses: 40,
            translation: "The Tidings",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 79,
            englishName: "An-Nazi'at",
            arabicName: "النازعات",
            revelationType: "MECCAN",
            versesRange: "46 VERSES",
            totalVerses: 46,
            translation: "Those who drag forth",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 80,
            englishName: "'Abasa",
            arabicName: "عبس",
            revelationType: "MECCAN",
            versesRange: "42 VERSES",
            totalVerses: 42,
            translation: "He Frowned",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 81,
            englishName: "At-Takwir",
            arabicName: "التكوير",
            revelationType: "MECCAN",
            versesRange: "29 VERSES",
            totalVerses: 29,
            translation: "The Overthrowing",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 82,
            englishName: "Al-Infitar",
            arabicName: "الإنفطار",
            revelationType: "MECCAN",
            versesRange: "19 VERSES",
            totalVerses: 19,
            translation: "The Cleaving",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 83,
            englishName: "Al-Mutaffifin",
            arabicName: "المطففين",
            revelationType: "MECCAN",
            versesRange: "36 VERSES",
            totalVerses: 36,
            translation: "The Defrauding",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 84,
            englishName: "Al-Inshiqaq",
            arabicName: "الإنشقاق",
            revelationType: "MECCAN",
            versesRange: "25 VERSES",
            totalVerses: 25,
            translation: "The Sundering",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 85,
            englishName: "Al-Buruj",
            arabicName: "البروج",
            revelationType: "MECCAN",
            versesRange: "22 VERSES",
            totalVerses: 22,
            translation: "The Mansions of the Stars",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 86,
            englishName: "At-Tariq",
            arabicName: "الطارق",
            revelationType: "MECCAN",
            versesRange: "17 VERSES",
            totalVerses: 17,
            translation: "The Nightcommer",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 87,
            englishName: "Al-A'la",
            arabicName: "الأعلى",
            revelationType: "MECCAN",
            versesRange: "19 VERSES",
            totalVerses: 19,
            translation: "The Most High",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 88,
            englishName: "Al-Ghashiyah",
            arabicName: "الغاشية",
            revelationType: "MECCAN",
            versesRange: "26 VERSES",
            totalVerses: 26,
            translation: "The Overwhelming",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 89,
            englishName: "Al-Fajr",
            arabicName: "الفجر",
            revelationType: "MECCAN",
            versesRange: "30 VERSES",
            totalVerses: 30,
            translation: "The Dawn",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 90,
            englishName: "Al-Balad",
            arabicName: "البلد",
            revelationType: "MECCAN",
            versesRange: "20 VERSES",
            totalVerses: 20,
            translation: "The City",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 91,
            englishName: "Ash-Shums",
            arabicName: "الشمس",
            revelationType: "MECCAN",
            versesRange: "15 VERSES",
            totalVerses: 15,
            translation: "The Sun",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 92,
            englishName: "Al-Layl",
            arabicName: "الليل",
            revelationType: "MECCAN",
            versesRange: "21 VERSES",
            totalVerses: 21,
            translation: "The Night",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 93,
            englishName: "Ad-Duhaa",
            arabicName: "الضحى",
            revelationType: "MECCAN",
            versesRange: "11 VERSES",
            totalVerses: 11,
            translation: "The Morning Hours",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 94,
            englishName: "Ash-Sharh",
            arabicName: "الشرح",
            revelationType: "MECCAN",
            versesRange: "8 VERSES",
            totalVerses: 8,
            translation: "The Relief",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 95,
            englishName: "At-Tin",
            arabicName: "التين",
            revelationType: "MECCAN",
            versesRange: "8 VERSES",
            totalVerses: 8,
            translation: "The Fig",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 96,
            englishName: "Al-'Alaq",
            arabicName: "العلق",
            revelationType: "MECCAN",
            versesRange: "19 VERSES",
            totalVerses: 19,
            translation: "The Clot",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 97,
            englishName: "Al-Qadr",
            arabicName: "القدر",
            revelationType: "MECCAN",
            versesRange: "5 VERSES",
            totalVerses: 5,
            translation: "The Power",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 98,
            englishName: "Al-Bayyinah",
            arabicName: "البينة",
            revelationType: "MEDINAN",
            versesRange: "8 VERSES",
            totalVerses: 8,
            translation: "The Clear Proof",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 99,
            englishName: "Az-Zalzalah",
            arabicName: "الزلزلة",
            revelationType: "MEDINAN",
            versesRange: "8 VERSES",
            totalVerses: 8,
            translation: "The Earthquake",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 100,
            englishName: "Al-'Adiyat",
            arabicName: "العاديات",
            revelationType: "MECCAN",
            versesRange: "11 VERSES",
            totalVerses: 11,
            translation: "The Courser",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 101,
            englishName: "Al-Qari'ah",
            arabicName: "القارعة",
            revelationType: "MECCAN",
            versesRange: "11 VERSES",
            totalVerses: 11,
            translation: "The Calamity",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 102,
            englishName: "At-Takathur",
            arabicName: "التكاثر",
            revelationType: "MECCAN",
            versesRange: "8 VERSES",
            totalVerses: 8,
            translation: "The Rivalry in world increase",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 103,
            englishName: "Al-'Asr",
            arabicName: "العصر",
            revelationType: "MECCAN",
            versesRange: "3 VERSES",
            totalVerses: 3,
            translation: "The Declining Day",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 104,
            englishName: "Al-Humazah",
            arabicName: "الهمزة",
            revelationType: "MECCAN",
            versesRange: "9 VERSES",
            totalVerses: 9,
            translation: "The Traducer",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 105,
            englishName: "Al-Fil",
            arabicName: "الفيل",
            revelationType: "MECCAN",
            versesRange: "5 VERSES",
            totalVerses: 5,
            translation: "The Elephant",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 106,
            englishName: "Quraysh",
            arabicName: "قريش",
            revelationType: "MECCAN",
            versesRange: "4 VERSES",
            totalVerses: 4,
            translation: "Quraysh",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 107,
            englishName: "Al-Ma'un",
            arabicName: "الماعون",
            revelationType: "MECCAN",
            versesRange: "7 VERSES",
            totalVerses: 7,
            translation: "The Small kindnesses",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 108,
            englishName: "Al-Kawthar",
            arabicName: "الكوثر",
            revelationType: "MECCAN",
            versesRange: "3 VERSES",
            totalVerses: 3,
            translation: "The Abundance",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 109,
            englishName: "Al-Kafirun",
            arabicName: "الكافرون",
            revelationType: "MECCAN",
            versesRange: "6 VERSES",
            totalVerses: 6,
            translation: "The Disbelievers",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 110,
            englishName: "An-Nasr",
            arabicName: "النصر",
            revelationType: "MEDINAN",
            versesRange: "3 VERSES",
            totalVerses: 3,
            translation: "The Divine Support",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 111,
            englishName: "Al-Masad",
            arabicName: "المسد",
            revelationType: "MECCAN",
            versesRange: "5 VERSES",
            totalVerses: 5,
            translation: "The Palm Fiber",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 112,
            englishName: "Al-Ikhlas",
            arabicName: "الإخلاص",
            revelationType: "MECCAN",
            versesRange: "4 VERSES",
            totalVerses: 4,
            translation: "The Sincerity",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 113,
            englishName: "Al-Falaq",
            arabicName: "الفلق",
            revelationType: "MECCAN",
            versesRange: "5 VERSES",
            totalVerses: 5,
            translation: "The Daybreak",
            juzId: 30,
          ),
          JuzSurahModel(
            number: 114,
            englishName: "An-Nas",
            arabicName: "الناس",
            revelationType: "MECCAN",
            versesRange: "6 VERSES",
            totalVerses: 6,
            translation: "Mankind",
            juzId: 30,
          ),
        ],
      ),
    ];
  }
}
